update misc and services configs

diff --git a/misc/build-threads b/misc/build-threads
--- a/misc/build-threads
+++ b/misc/build-threads
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Builds sessions service
+# Builds threads service
 #
 
 set -e
@@ -10,36 +10,39 @@ declare -A pause=(["prod"]="30s" ["stage"]="20s")
 
 # env BUILD_DIR, ENV
 
-touch "$BUILD_DIR/logs/sessions.log"
+touch "$BUILD_DIR/logs/threads.log"
 
-echo "*** logging in $BUILD_DIR/logs/sessions.log"
+echo "*** logging in $BUILD_DIR/logs/threads.log"
 
 exec 7<&1
-exec &> "$BUILD_DIR/logs/sessions.log"
+exec &> "$BUILD_DIR/logs/threads.log"
 
 # build 
-echo "*** building sessions"
+echo "*** building threads"
 
-cd $BUILD_DIR/gallery/server/sessions
+cd $BUILD_DIR/gallery/server/threads
 echo "*** pwd = $(pwd)"
 go version
 [ $? -ne 0 ] && echo "*** go is not installed, exit." && exit 1
 go env -w "CGO_ENABLED=1"
-
 go build -v -buildvcs=false ./cmd/grpc/
+[ $? -ne 0 ] && echo "*** build failed, exit." && exit 1
+
+go build -v -buildvcs=false ./cmd/http/
 [ $? -ne 0 ] && echo "*** build failed, exit." && exit 1
 
 # stop
 set +e
+
 for host in ${HOSTS[@]}; do
-    echo "*** mv sessions on $host"
-    ssh "$host" "/srv/misc/scripts/stop_sessions.sh"
+    echo "*** mv threads on $host"
+    ssh "$host" "/srv/misc/scripts/stop_threads.sh"
 
-    scp grpc "$host:/srv/gallery/$ENV/sessions/"
-    scp http "$host:/srv/gallery/$ENV/sessions/"
+    scp grpc "$host:/srv/gallery/$ENV/threads/"
+    scp http "$host:/srv/gallery/$ENV/threads/"
 
-    echo "*** start sessions on $host"
-    ssh "$host" "/srv/misc/scripts/start_sessions.sh"
+    echo "*** start threads on $host"
+    ssh "$host" "/srv/misc/scripts/start_threads.sh"
 
     sleep ${pause[$ENV]} # let cluster restart
 done
